"""initial

Revision ID: 6ff9ea8bfd3d
Revises:
Create Date: 2026-03-20 21:35:18.312190

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6ff9ea8bfd3d"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    op.execute("CREATE SEQUENCE categories_id_seq START 1000")
    op.execute("CREATE SEQUENCE sub_categories_id_seq START 1000")
    op.execute("CREATE SEQUENCE product_id_seq START 1000")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categories",
        sa.Column("categories_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("image", sa.String(), nullable=True),
        sa.Column("recommended", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("categories_id"),
    )
    op.create_index(op.f("ix_categories_title"), "categories", ["title"], unique=False)
    op.create_table(
        "subcategories",
        sa.Column(
            "sub_categories_id", sa.Integer(), autoincrement=True, nullable=False
        ),
        sa.Column("sub_categories_title", sa.String(), nullable=False),
        sa.Column("sub_categories_image", sa.String(), nullable=False),
        sa.Column("sub_categories_recommended", sa.Boolean(), nullable=False),
        sa.Column("categories_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["categories_id"],
            ["categories.categories_id"],
        ),
        sa.PrimaryKeyConstraint("sub_categories_id"),
    )
    op.create_index(
        op.f("ix_subcategories_categories_id"),
        "subcategories",
        ["categories_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_subcategories_sub_categories_title"),
        "subcategories",
        ["sub_categories_title"],
        unique=False,
    )
    op.create_table(
        "products",
        sa.Column("products_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("price", sa.Integer(), nullable=False),
        sa.Column("discount", sa.Integer(), nullable=True),
        sa.Column("product_type", sa.String(), nullable=False),
        sa.Column("images", sa.JSON(), nullable=False),
        sa.Column("recommended", sa.Boolean(), nullable=True),
        sa.Column("sub_category_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["sub_category_id"],
            ["subcategories.sub_categories_id"],
        ),
        sa.PrimaryKeyConstraint("products_id"),
    )
    op.create_index(
        op.f("ix_products_sub_category_id"),
        "products",
        ["sub_category_id"],
        unique=False,
    )
    op.create_index(op.f("ix_products_title"), "products", ["title"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_products_title"), table_name="products")
    op.drop_index(op.f("ix_products_sub_category_id"), table_name="products")
    op.drop_table("products")
    op.drop_index(
        op.f("ix_subcategories_sub_categories_title"), table_name="subcategories"
    )
    op.drop_index(op.f("ix_subcategories_categories_id"), table_name="subcategories")
    op.drop_table("subcategories")
    op.drop_index(op.f("ix_categories_title"), table_name="categories")
    op.drop_table("categories")

    op.execute("DROP SEQUENCE IF EXISTS categories_id_seq")
    op.execute("DROP SEQUENCE IF EXISTS sub_categories_id_seq")
    op.execute("DROP SEQUENCE IF EXISTS product_id_seq")
    # ### end Alembic commands ###
